main/urls.py
from django.conf.urls import url, patterns, handler404
import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^edit_profile/$',views.edit_profile,name='edit_profile'),
    url(r'^about/$',views.about,name='about'),
    url(r'^viewProfile/(?P<userId>[0-9]+)/', views.viewProfile, name="view_profile"),
    url(r'^run/new/', views.uploadRun, name="new_run"),
    url(r'^run/(?P<runid>[0-9]+)/', views.viewRun, name="view_run"),
    url(r'^task/manage/', views.manageTask, name="manage_task"),
    url(r'^task/new/', views.uploadTask, name="new_task"),
    url(r'^task/(?P<taskid>[0-9]+)/delete', views.deleteTask, name="delete_task"),
    url(r'^task/(?P<taskid>[0-9]+)/edit', views.editTask, name="edit_task"),
    url(r'^task/(?P<taskid>[0-9]+)/', views.viewTask, name="view_task"),
    url(r'^track/new/', views.uploadTrack, name="new_track"),
    url(r'^track/manage/', views.manageTrack, name="manage_track"),
    url(r'^track/(?P<trackid>[0-9]+)/delete', views.deleteTrack, name="delete_track"),
    url(r'^track/(?P<trackid>[0-9]+)/edit', views.editTrack, name="edit_track"),
    url(r'^track/(?P<trackid>[0-9]+)/', views.viewTrack, name="view_track"),
    url(r'^genre/new/', views.uploadGenre, name="new_genre"),
    url(r'^genre/manage/', views.manageGenre, name="manage_genre"),
    url(r'^genre/(?P<genreid>[0-9]+)/delete', views.deleteGenre, name="delete_genre"),
    url(r'^genre/(?P<genreid>[0-9]+)/edit', views.editGenre, name="edit_genre"),
    url(r'^browse/task/(?P<taskid>[0-9]+)/$', views.browseComplete, name='browseComplete'),
    url(r'^browse/(?P<trackid>[0-9]+)/$', views.browseTrack, name='browseTrack'),
    url(r'^browse/$', views.browse, name='browse'),
    url(r'^search/results', views.search, name="searchRes"),
    url(r'^search/$', views.searchForm, name='search'),
    url(r'^getOrgsJson/$', views.getOrgsJson),
    url(r'^getUsrnameJson/$', views.getUsrnameJson),
    url(r'^getNameJson/$', views.getNameJson),
    url(r'^getRunNameJson/$', views.getRunNameJson),
    url(r'^getTrackInfoJson/$', views.getTrackInfoJson),
    url(r'^getTaskInfoJson/$', views.getTaskInfoJson),
    url(r'^getTasksJson/$', views.getTasksJson),
    )

trec/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^main/', include('main.urls')),
    url(r'^$', RedirectView.as_view(url="/main/", permanent=True), name='rootNoparams'),)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_PATH)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save
from django.contrib.auth.models import User
from django.utils import timezone

def upload_profile(instance, filename):
    return "profile/%s/%s" % (instance.user.username, filename)

class Researcher(models.Model):
    def __unicode__(self):
        return u'{0}'.format(self.display_name)

    user = models.OneToOneField(
        User,
        on_delete = models.CASCADE,
        primary_key = True
    )
    profile_picture = models.ImageField(upload_to=upload_profile, blank=False)
    website = models.CharField(max_length=64, unique=False, blank=True)
    display_name = models.CharField(max_length=128, unique=False)
    organization = models.CharField(max_length=128, unique=False, blank=True)

class Genre(models.Model):
    def __unicode__(self):
        return u'{0}'.format(self.title)
    title = models.CharField(max_length=64, unique=True)

class Track(models.Model):
    def __unicode__(self):
        return u'{0}'.format(self.title)
    title = models.CharField(max_length = 64, unique=True)
    track_url = models.URLField(max_length=200)
    description = models.CharField(max_length=400)
    genre = models.ForeignKey(
        Genre, on_delete=models.PROTECT,
    )

class Task(models.Model):
    def __unicode__(self):
        return u'{0}'.format(self.title)

    track = models.ForeignKey(
        Track,
        on_delete = models.CASCADE
    )
    title = models.CharField(max_length = 64, unique=True)
    task_url = models.URLField(max_length=200)
    description = models.CharField(max_length = 400)
    year = models.PositiveSmallIntegerField()
    judgement_file = models.FileField(upload_to="trec_tracks/%Y/%m/")

class RunFile(models.Model):
    result_file = models.FileField(upload_to="trec_upload/%Y/%m/%d/")

class Run(models.Model):
    def save(self, *args, **kwargs):
        self.datetime = timezone.now()
        super(Run, self).save(*args, **kwargs)
    # Run_type enums
    RT_Automatic = "AU"
    RT_Manual = "MA"
    Run_type_choices = (
        (RT_Automatic, "Automatic"),
        (RT_Manual, "Manual"),
    )

    # Query_type enums
    QT_Title_only = "TO"
    QT_Title_Desc = "TD"
    QT_Desc_only = "DO"
    QT_All_fields = "AF"
    QT_Other = "UF" # Unknown fields
    Query_type_choices = (
        (QT_Title_only, "Title only"),
        (QT_Title_Desc, "Title + description"),
        (QT_Desc_only, "Description"),
        (QT_All_fields, "All"),
        (QT_Other, "Other"),
    )

    #Feedback_type enums
    FT_None = "NF"
    FT_Pseudo = "PF"
    FT_Relevance = "RF"
    FT_Other = "OF"
    Feedback_type_choices = (
        (FT_None, "None"),
        (FT_Pseudo, "Pseudo"),
        (FT_Relevance, "Relevance"),
        (FT_Other, "Other"),
    )

    researcher = models.ForeignKey(Researcher, on_delete=models.CASCADE)
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    name = models.CharField(max_length=64, unique=False)
    datetime = models.DateTimeField()
    result_file = models.OneToOneField(
        RunFile,
        on_delete = models.CASCADE,
    )
    description = models.CharField(max_length=400, unique=False)
    run_type = models.CharField(max_length=2, choices=Run_type_choices)
    query_type = models.CharField(max_length=2, choices=Query_type_choices)
    feedback_type = models.CharField(max_length=2, choices=Feedback_type_choices)
    map = models.DecimalField(max_digits=15, decimal_places=12)
    p10 = models.DecimalField(max_digits=15, decimal_places=12)
    p20 = models.DecimalField(max_digits=15, decimal_places=12)

main/views.py
from django.shortcuts import render, render_to_response, redirect, get_object_or_404, get_list_or_404
from django.contrib.auth.decorators import login_required

from main.models import Task, Track, Run, Researcher, Genre
from main.forms import RunForm, RunFileForm, UserForm, UserProfileForm,\
    TaskForm, TrackForm, GenreForm, ReturnUrlForm, BrowseTrackForm, BrowseTaskForm, BrowseTaskSortForm

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.models import User
from django.template import RequestContext
from django.utils import timezone

from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout

from util import trec, viewhelper
from util.dataparser import *

import json
from django.core import serializers
from django.core.serializers.json import DjangoJSONEncoder
from django.core.urlresolvers import reverse
from django.contrib.admin.views.decorators import staff_member_required
from decimal import *

from chartit import *

def index(request):
    context_dict = {}

    best_list = Run.objects.all().order_by('-p10', '-p20', '-map')[:10]
    context_dict["best"] = best_list
    recent_list = Run.objects.all().order_by('-datetime')[:10]
    context_dict["recent"] = recent_list

    return render(request, 'main/index.html', context_dict)

def browse(request):
    contextDict = {}
    if request.method == "GET":
        browse_form = BrowseTrackForm()
    else:
        browse_form = BrowseTrackForm(request.POST)
        if browse_form.is_valid():
            track = browse_form.cleaned_data["track"]
            return HttpResponseRedirect(reverse("browseTrack", kwargs={"trackid":track.id}))
    contextDict["action_url"] = reverse("browse")
    contextDict["submit_msg"] = "Submit"
    contextDict["form"] = browse_form
    return render(request, 'main/browse.html', contextDict)

def browseTrack(request, trackid):
    contextDict = {}
    thisTrack = get_object_or_404(Track, id=trackid)
    sort_type = ""
    sort_order = ""
    if request.method == "GET":
        browse_form = BrowseTaskForm(track=thisTrack)
        sort_form = BrowseTaskSortForm()
    else:
        browse_form = BrowseTaskForm(request.POST, track=thisTrack)
        sort_form = BrowseTaskSortForm(data=request.POST)
        if browse_form.is_valid():
            if sort_form.is_valid():
                sort_type = sort_form.cleaned_data["sortOn"]
                sort_order = sort_form.cleaned_data["sortOrd"]
            returnUrl = reverse("browseComplete", kwargs={"taskid":browse_form.cleaned_data["task"].id})
            returnUrl += "?userRuns=" + str("my_tracks" in request.POST)
            returnUrl += "&pageSize=" + browse_form.cleaned_data["size"]
            if len(sort_type) != 0:
                returnUrl += "&Sort=" + sort_type.strip() + "&Order=" + sort_order.strip()
            return HttpResponseRedirect(returnUrl)
    contextDict["track"] = thisTrack
    contextDict["action_url"] = reverse("browseTrack", kwargs={"trackid":trackid})
    contextDict["submit_msg"] = "Browse runs for this task"
    contextDict["form"] = browse_form
    contextDict["sort_form"] = sort_form
    return render(request, 'main/browse.html', contextDict)

def browseComplete(request, taskid):
    reverseLookup = {"DA": "datetime",
                     "P1": "p10",
                     "P2": "p20",
                     "MA": "map",
                     "FT": "feedback_type",
                     "RT": "run_type",
                     "QT": "query_type",
                     "UO": "researcher__organization",
                     "UU": "researcher__user_username",
                     "UN": "researcher__display_name",
                     "TL": "name",}
    pageNo = request.GET.get("page", "1")
    pageSize = request.GET.get("pageSize", "10")
    errorSorting = False
    contextDict = {}
    userRunsRequested = False
    thisTask = get_object_or_404(Task, id=taskid)
    if request.user.is_authenticated():
        if request.GET.get('userRuns') == "True":
            userRunsRequested = True
    filtered_objects = Run.objects.filter(task__id=taskid)
    # Get averages BEFORE paginating and limiting results
    averages = trec.getMaximums(filtered_objects)
    if userRunsRequested:
        filtered_objects = filtered_objects.filter(researcher__user=request.user)
    try:
        if pageSize != "all":
            pageSize = int(pageSize)
        else:
            pageSize = filtered_objects.count()
    except:
        pageSize = 10
    sortType = request.GET.get('Sort')
    orderType = request.GET.get('Order')
    if orderType is not None:
        orderType = orderType.strip()
    else:
        orderType = "DE"
    if sortType is not None:
        sortType = sortType.strip()
    else:
        sortType = ""

    if len(sortType) > 0:
        if reverseLookup.has_key(sortType):
            sortStr = reverseLookup[sortType]
            if orderType == "DE":
                sortStr = "-" + sortStr
            filtered_objects = filtered_objects.order_by(sortStr)
        else:
            if sortType == "AL":
                if orderType == "DE":
                    filtered_objects = filtered_objects.order_by("-p10", "-p20", "-map")
                else:
                    filtered_objects = filtered_objects.order_by("p10", "p20", "map")
            else:
                errorSorting = True
    paginator = Paginator(filtered_objects, pageSize)
    try:
        page = paginator.page(pageNo)
    except PageNotAnInteger:
        page = paginator.page(1)
    except EmptyPage:
        page = paginator.page(paginator.num_pages)
    filtered_objects = page.object_list
    contextDict["averages"] = averages
    contextDict["errorSorting"] = errorSorting
    contextDict["task"] = thisTask
    contextDict["track"] = thisTask.track
    contextDict["user"] = request.user
    contextDict["runs"] = page
    contextDict["userRunsRequested"] = userRunsRequested
    contextDict["pageSize"] = pageSize
    cht = None
    # Don't show a graph if no results will be shown
    if len(filtered_objects) > 0:
        if request.user.is_authenticated():
            # Need to get the IDs in our current list since Django does not allow to filter after slicing
            our_id = filtered_objects.values_list("id", flat=True)
            our_runs = Run.objects.filter(id__in=our_id)
            myRuns = our_runs.filter(researcher__user=request.user)
            otherRuns = our_runs.exclude(researcher__user=request.user)
        else:
            myRuns = []
            otherRuns = filtered_objects

        if len(myRuns) > 0:
            ds = DataPool(
               series=
                [{'options': {
                    'source': otherRuns},
                  'terms': [
                    'datetime',
                    'map',
                    'p10',
                    'p20']},
                 {'options': {
                    'source': myRuns},
                  'terms': [
                      {'your_datetime':'datetime'},
                      {'Your map':'map'},
                      {'Your p10':'p10'},
                      {'Your p20':'p20'}]}
                 ])
            cht = Chart(
            datasource = ds,
            series_options =
              [{'options':{
                  'type': 'line',
                  'stacking': False},
                'terms':{
                  'datetime': [
                    'p10',
                    'p20',
                    'map'],
                    'your_datetime': [
                        'Your p10',
                        'Your p20',
                        'Your map'
                    ]
                  }}],
            chart_options =
              {'title': {
                   'text': 'P10, P20 and Map scores over time'},
               'xAxis': {
                    'title': {
                       'text': 'Date & time'},
                    'labels': {
                        'formatter':'formatter'
                    }},
                'tooltip': {
                    'formatter':'tooltipFormatter'
                },
               'yAxis': {
                   'title': {
                       'text': 'Score'
                   }}})
        else:
            ds = DataPool(
               series=
                [{'options': {
                    'source': otherRuns},
                  'terms': [
                    'datetime',
                    'map',
                    'p10',
                    'p20']}])
            cht = Chart(
            datasource = ds,
            series_options =
              [{'options':{
                  'type': 'line',
                  'stacking': False},
                'terms':{
                  'datetime': [
                    'p10',
                    'p20',
                    'map'],
                  }}],
            chart_options =
              {'title': {
                   'text': 'P10, P20 and Map scores over time'},
               'xAxis': {
                    'title': {
                       'text': 'Date & time'},
                    'labels': {
                        'formatter':'formatter'
                    }},
                'tooltip': {
                    'formatter':'tooltipFormatter'
                },
               'yAxis': {
                   'title': {
                       'text': 'Score'
                   }
               }})
    if cht is not None:
        contextDict["chart"] = cht
    return render(request, 'main/browseTask.html', contextDict)

@login_required
def uploadRun(request):
    contextDict = {}
    finish = False
    fail = False
    results = {}
    averages = []
    if request.method == "GET":
        upl_form = RunForm()
        upl_file_form = RunFileForm()
    else:
        upl_form = RunForm(request.POST)
        upl_file_form = RunFileForm(request.POST, request.FILES)

templates/main/about.html
{% extends "main/base.html" %}

{% load staticfiles %}

{% block title %} About{% endblock %}

{% block h1 %} About Trec Feed {% endblock %}

{% block body_block %}

	<!-- Page card title !-->
	<h2>About tFeed</h2>
	<hr />
	<!-- /Page card title !-->

	<h4>With tFeed you can...</h4>
	<div class="col-lg-12 col-md-12 col-sm-12 how-to">
		<h5>Upload your run (.res files) and get your results</h5>
		<h5>Evaluate your performance</h5>
		<h5>Compare it to others' performance</h5>
		<h5>Get information about each track, task and run</h5>
	</div>
	<br/><br/>
	<h3>Developed by...</h3><hr/>
	<div class="col-lg-12 col-md-12 col-sm-12">
		<div class="col-lg-3 col-md-6 col-sm-6 makers-of">
			<img class="img-circle img" src="{% static 'images/pablo.jpg' %}" alt="Image of Pablo" /><br/>
			<h4>Pablo Arteaga - 2144641A</h4>
		</div>
		<div class="col-lg-3 col-md-6 col-sm-6 makers-of">
			<img class="img-circle img" src="{% static 'images/maria.jpg' %}" alt="Image of Maria" /><br/>
			<h4>Maria-Luiza Koleva - 2127555K</h4>
		</div>
		<div class="col-lg-3 col-md-6 col-sm-6 makers-of">
			<img class="img-circle img" src="{% static 'images/shaun.jpg' %}" alt="Image of Shaun" /><br/>
			<h4>Shaun Macdonald - 1005872M</h4>
		</div>
		<div class="col-lg-3 col-md-6 col-sm-6 makers-of">
			<img class="img-circle img" src="{% static 'images/aigars.jpg' %}" alt="Image of Aigars" /><br/>
			<h4>Aigars Reiters - 2148261R</h4>
		</div>
	</div>
{% endblock %}

templates/main/base_forms.html
{% extends "main/base.html" %}

{% load staticfiles %}
{% load widget_tweaks %}

{% block body_block %}
{% block insert_block %}{% endblock %}
{% if new %}
    {% if valid %}
        {% block ok_upload %}
        {% endblock %}
    {% endif %}
    {% if error %}
        {% block error_upload %}{% endblock %}
    {% endif %}
{% else %}
    {% if valid %}
        {% block ok_edit %}{% endblock %}
    {% endif %}
    {% if error %}
        {% block error_edit %}{% endblock %}
    {% endif %}
{% endif %}
<form id="upload_generic" method="post" action="{{ retUrl }}" enctype="multipart/form-data" data-parsley-validate >
    {% csrf_token %}
    {{ form.as_p }}
	<div class="alert alert-info col-lg-12 col-md-12 col-sm-12">
		{% block suggest_add %}Enter the information above and press the button below when you're done.{% endblock %}
	</div>
	<div class="col-lg-6 col-md-12 col-sm-12 col-lg-offset-3">
		<input class="btn btn-info btn-block" type="submit" name="submit" value="{% if new %}Create{% else %}Update{% endif %}">
	</div>

</form>

{% endblock %}

templates/main/browse.html
{% extends "main/base.html" %}

{% load staticfiles %}

{% block title %}Browse{% endblock %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/autoform.css' %}">
{% endblock %}
{% block h1 %}Browse{% endblock %}
{% block body_block %}
	{% if sort_form %}
		<script src="{% static 'js/jquery.collapse.js' %}"></script>
    	<script src="{% static 'js/jquery.collapse_cookie_storage.js' %}"></script>
    	<script src="{% static 'js/jquery.collapse_storage.js' %}"></script>
		<script src="{% static 'js/browseForm.js' %}"></script>
	{% endif %}
	{% if track %}
		<script src="{% static 'js/ajaxBrowseTask.js' %}"></script>
	{% else %}
		<script src="{% static 'js/ajaxBrowseTrack.js' %}"></script>
	{% endif %}

	<!-- Page card title !-->
	<h2>Please select search criteria</h2>
	<hr/>
	<!-- /Page card title !-->
	{% if track %}
		<h5 class="alert alert-info">You are selecting tasks for <a href="{% url 'view_track' trackid=track.id %}">track {{ track.title }}</a>. You can go back and
			<a href="{% url 'browse' %}">select another track</a></h5>
	{% endif %}
<div>
	<div id="generalInfo">
		<table class="table table-striped table-bordered" id="tableInfo">
			<tbody>

			</tbody>
		</table>
	</div>
    <form id="browse" method="post" action="{{ action_url }}" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
		{% if sort_form %}
			<h3 id="form" class="search-forms"><a href=#" id="toggle"><span class="glyphicon glyphicon-plus"></span>Sorting options</a></h3>
			<div id="sortForm">
				<h5 class="alert alert-info">Tip: You can also sort by clicking on the headers of the table</h5>
				{{ sort_form.as_p }}
			</div>
		{% endif %}
		<div class="col-lg-6 col-lg-offset-3">
        <input type="submit" name="submit" value="{{ submit_msg }}" class="btn btn-info btn-block">
		<!-- We only want to show the option to 'show my runs' when selecting a task -->
		{% if user.is_authenticated %}
			{% if track %}
				<input type="submit" name="my_tracks" value="Find my own runs" class="btn btn-info btn-block">
			{% endif %}
		{% endif %}
		</div>
    </form>
</div>
{% endblock %}

templates/main/browseTask.html
{% extends "main/base.html" %}
{% load staticfiles %}
{% block title %}Browse{% endblock %}
{% block h1 %}Browse{% endblock %}
{% block head %}
<script src="{% static 'js/jquery-dateFormat.min.js' %}"></script>
<script src="{% static 'js/graphFormatter.js' %}"></script>
<script src="{% static 'js/highcharts.js' %}"></script>
{% if chart %}
{% load chartit %}
{{ chart|load_charts:"chart" }}
{% endif %}
{% endblock %}
{% block body_block %}


	<!-- Page card title !-->
	<h2>Browsing {{ task }}</h2>
	<hr/>
	<!-- /Page card title !-->
	{% if errorSorting %}
		<h3 class="alert alert-warning">The items could not be sorted. Please, try again later</h3>
	{% endif %}

	{% if runs %}
		<div class="table-responsive">
		<h4>Runs on task <a href="{% url 'view_task' taskid=task.id %}">{{ task.title }}</a></h4>
			<h5>This task is on track <a href="{% url 'view_track' trackid=track.id %}">{{ track.title }}</a></h5>
			{% if userRunsRequested %}
				<h5>You are only seeing your own runs</h5>
			{% endif %}
			{% if runs.has_previous %}
	            <a href="?page={{ runs.previous_page_number }}&pageSize={{ pageSize }}&userRuns={{ userRunsRequested }}">&#8592; prev</a>
	        {% endif %}

	        <span class="current">
	            Page {{ runs.number }} of {{ runs.paginator.num_pages }}.
        	</span>

    	    {% if runs.has_next %}
	            <a href="?page={{ runs.next_page_number }}&pageSize={{ pageSize }}&userRuns={{ userRunsRequested }}">next &#8594;</a>
        	{% endif %}
			<table class="sortable table table-striped table-bordered table-hover">
				<thead class="thead-inverse">
					<tr>
						<th>Uploaded on</th>
						<th>Researcher</th>
						<th>Organization</th>
						<th>Run</th>
						<th>Map</th>
						<th>p10</th>
						<th>p20</th>
					</tr>
				</thead>
				<tbody>
				{% for run in runs %}
					{% if user %}
						{% if user = run.researcher.user %}
							<tr class="your-run">
						{% else %}
							<tr>
						{% endif %}
					{% else %}
						<tr>
					{% endif %}
						<td>{{ run.datetime|date:"d-m-Y H:m" }}</td>
						<td><a href="{% url 'view_profile' userId=run.researcher.user.id %}">{{ run.researcher }}</a></td>
						<td>{{ run.researcher.organization|default:"Not provided" }}</td>
						<td><a href="{% url 'view_run' runid=run.id %}">{{ run.name }}</a></td>
						<td>{{ run.map }}</td>
						<td>{{ run.p10 }}</td>
						<td>{{ run.p20 }}</td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
		{% if chart %}
		<div id="chart" class="chart">

		</div>
		{% endif %}
		{% if averages %}
			<h4>Aggregated results from other participants</h4>
			<table class="sortable table table-striped table-bordered table-hover order-column">
				<thead class="thead-inverse">
					<tr>
						<th>Measure</th>
						<th>Value</th>
					</tr>
				</thead>

				<tbody>
					{% for average in averages %}
						<tr>
							<td>{{ average.0 }}</td>
							<td>{{ average.1 }}</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		{% endif %}
	{% else %}
		<h3 class="alert alert-warning">There are no Runs for this Task</h3>
	{% endif %}

{% endblock %}

templates/main/manageGenre.html
{% extends "main/base.html" %}

{% load staticfiles %}

{% block title %}Genre Manager{% endblock %}
{% block h1 %}Genre Manager{% endblock %}
{% block body_block %}

<h2>Manage Genres</h2>
<hr />


<div class="col-lg-6 col-md-12 col-sm-12 col-lg-offset-3">
    <a href="{% url 'new_genre' %}" class="btn btn-info btn-block" role="button">Create new Genre</a>
</div>
{% if list %}
<div class="col-lg-12 col-md-12 col-sm-12">
	<h4>These are the current genres</h4>
</div>
<div class="col-lg-12 col-md-12 col-sm-12">
	<table class="table table-responsive table-borderless" id="manage-table">
        <thead>
            <th></th>
            <th></th>
            <th></th>
        </thead>
        <tbody>
            {% for genre in list %}
                <tr>
                    <td><h4>{{ genre.title }}</h4></td>
                    <td><a href="{% url 'edit_genre' genreid=genre.id %}" class="btn btn-info btn-block">Edit</a></td>
                    <td><a href="{% url 'delete_genre' genreid=genre.id %}" class="btn btn-info btn-block">Delete</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% else %}
<h3 class="alert alert-warning">There are no Genres yet</h3>
{% endif %}

{% endblock %}

templates/main/viewRun.html
{% extends "main/base.html" %}

{% load staticfiles %}

{% block title %}Run Viewer{% endblock %}
{% block h1%}Run Viewer{% endblock %}

{% block body_block %}

<h2>Run "{{ run.name }}" by {{ profile.display_name }}</h2><hr/>
<h4>Details</h4>

<table class="table table-striped table-bordered table-hover">
    <tr>
        <td>Researcher name</td>
        <td><a href="{% url 'view_profile' userId=profile.user.id %}">{{ profile.display_name }}</a></td>
    </tr>
    <tr>
        <td>Researcher organization</td>
        <td>{{ profile.organization|default:"Not provided" }}</td>
    </tr>
    <tr>
        <td>Title</td>
        <td>{{ run.name }}</td>
    </tr>

    <tr>
        <td>Description</td>
        <td>{{ run.description }}</td>
    </tr>
    <tr>
        <td>Submitted at</td>
        <td>{{ run.datetime|date:"d-m-Y H:m" }}</td>
    </tr>
    <tr>
        <td>Run type</td>
        <td>{{ run.get_run_type_display }}</td>
    </tr>
    <tr>
        <td>Query type</td>
        <td>{{ run.get_query_type_display }}</td>
    </tr>
    <tr>
        <td>Feedback type</td>
        <td>{{ run.get_feedback_type_display }}</td>
    </tr>
    <tr>
        <td>Task</td>
        <td><a href="{% url 'view_task' taskid=run.task.id %}">{{ run.task.title }}</a></td>
    </tr>
    <tr>
        <td>Track</td>
        <td><a href="{% url 'view_track' trackid=run.task.track.id %}">{{ run.task.track.title}}</a></td>
    </tr>
    <tr>
        <td>Results</td>
        <td>
            <table class="table table-striped table-bordered table-hover">
                <tr>
                    <th>Measure</th>
                    <th>Score</th>
                </tr>
                <tr>
                    <td>Precision at 10 (P_10)</td>
                    <td>{{ run.p10 }}</td>
                </tr>
                <tr>
                    <td>Precision at 20 (P_20)</td>
                    <td>{{ run.p20 }}</td>
                </tr>
                <tr>
                    <td>Map (map)</td>
                    <td>{{ run.map }}</td>
                </tr>
            </table>
        </td>
    </tr>
</table>

{% endblock %}